#!/bin/sh

set_method(){ 
  case ${1:? setmethod: argument needed!} in 
    generate|list|get|methods|regions|os|spec) 
      setvar method GET;;
    create|init|start|stop|forcestop|destroy|assign|retry|restore|add|verify|add)
      setvar method POST ;;
    update)
      setvar method PUT;;
    delete|remove|cancel)
      setvar method DELETE;;
  esac
}

get_method(){ getvar method; }

set_endpoint(){ setvar endpoint ${BASE_URL:?BASE_URL corrupted!}/${1:?set_endpoint: argument needed!}; }

get_endpoint(){ getvar endpoint; }

extract_token(){ jq .accessToken; }

